export interface SpeechSection {
  title: string;
  text: string;
}

export const cleanSpeechText = (text: string): string => {
  if (!text) return '';
  return text
    .replace(/[\#\*\_`>]/g, '') // remove markdown syntax
    .replace(/<[^>]*>/g, '')    // remove HTML tags
    .replace(/https?:\/\/\S+/g, '') // remove URLs
    // Remove emojis and decorative icons
    .replace(/[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF]/g, '')
    .replace(/\b[0-9a-f]{24}\b/g, '') // remove 24-character hex MongoDB IDs
    .replace(/\s+/g, ' ') // remove double whitespaces
    .replace(/•/g, '') // remove bullet points
    .replace(/✓/g, '') // remove checkmarks
    .replace(/✗/g, '') // remove crossmarks
    .trim();
};

export const buildSpeechSections = (analysis: any): SpeechSection[] => {
  const sections: SpeechSection[] = [];
  if (!analysis) return sections;

  // 1. Intro
  let intro = `Legal Document Analysis.`;
  if (analysis.contractType && analysis.contractType !== 'Unknown') {
    intro += ` This is a ${analysis.contractType}.`;
  }
  if (analysis.riskScore) {
    const score = analysis.riskScore.score ?? (typeof analysis.riskScore === 'number' ? analysis.riskScore : 0);
    const label = analysis.riskScore.label || '';
    intro += ` The overall risk assessment is ${label}, with a score of ${score} out of 10.`;
  }
  sections.push({ title: 'Introduction', text: intro });

  // 2. Summary
  if (analysis.summary) {
    let summaryText = 'Executive Summary. ';
    if (Array.isArray(analysis.summary)) {
      summaryText += analysis.summary.join('. ');
    } else {
      summaryText += analysis.summary;
    }
    sections.push({ title: 'Executive Summary', text: summaryText });
  }

  // 3. Pros
  if (analysis.pros && analysis.pros.length > 0) {
    let prosText = 'Advantages identified. ';
    analysis.pros.forEach((pro: any, index: number) => {
      const proNum = `Advantage number ${index + 1}. `;
      if (typeof pro === 'string') {
        prosText += proNum + pro + '. ';
      } else {
        const clause = pro.clause ? `${pro.clause}. ` : '';
        const explanation = pro.explanation ? `${pro.explanation}. ` : '';
        const advice = pro.advice ? `Recommended advice: ${pro.advice}. ` : '';
        prosText += proNum + clause + explanation + advice;
      }
    });
    sections.push({ title: 'Advantages', text: prosText });
  }

  // 4. Concerns
  if (analysis.cons && analysis.cons.length > 0) {
    let consText = 'Concerns and risks identified. ';
    analysis.cons.forEach((con: any, index: number) => {
      const conNum = `Concern number ${index + 1}. `;
      if (typeof con === 'string') {
        consText += conNum + con + '. ';
      } else {
        const severity = con.severity ? `Severity is ${con.severity}. ` : '';
        const clause = con.clause ? `${con.clause}. ` : '';
        const explanation = con.explanation ? `${con.explanation}. ` : '';
        const advice = con.advice ? `Recommended action: ${con.advice}. ` : '';
        consText += conNum + severity + clause + explanation + advice;
      }
    });
    sections.push({ title: 'Concerns', text: consText });
  }

  // 5. Highlighted Clauses
  if (analysis.highlightedClauses && analysis.highlightedClauses.length > 0) {
    let clausesText = 'Highlighted Clauses. ';
    analysis.highlightedClauses.forEach((clause: any, index: number) => {
      const clauseNum = `Clause number ${index + 1}. `;
      if (typeof clause === 'string') {
        clausesText += clauseNum + clause + '. ';
      } else {
        const title = clause.title ? `${clause.title}. ` : '';
        const type = clause.type ? `Type is ${clause.type}. ` : '';
        const text = clause.text ? `Clause text is: ${clause.text}. ` : '';
        const explanation = clause.explanation ? `Explanation: ${clause.explanation}. ` : '';
        clausesText += clauseNum + title + type + text + explanation;
      }
    });
    sections.push({ title: 'Highlighted Clauses', text: clausesText });
  }

  // 6. Overall Advice
  if (analysis.overallAdvice) {
    sections.push({ title: 'Overall Advice', text: 'Overall Advice. ' + analysis.overallAdvice });
  }

  // 7. Disclaimer
  sections.push({
    title: 'Disclaimer',
    text: 'Disclaimer. This analysis is generated by an artificial intelligence model and does not constitute formal legal advice. Please consult with a qualified legal professional to verify this information.'
  });

  return sections.map(s => ({
    title: s.title,
    text: cleanSpeechText(s.text)
  })).filter(s => s.text.trim().length > 0);
};
